# Generated by Django 2.1.10 on 2019-08-21 14:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('remain_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('measurment', models.CharField(choices=[('piece', 'piece'), ('set', 'set')], max_length=200)),
                ('buy_date', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StorePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, unique=True)),
                ('discription', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=200, unique=True)),
                ('discription', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='car_type',
            field=models.ManyToManyField(to='spare.Vehicle'),
        ),
        migrations.AddField(
            model_name='item',
            name='store_place',
            field=models.ManyToManyField(to='spare.StorePlace'),
        ),
    ]
