# Generated by Django 2.1.10 on 2019-08-27 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spare', '0002_auto_20190821_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_code', models.CharField(max_length=200, unique=True)),
                ('place', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Buy',
            new_name='Purchase',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='remain_quantity',
            new_name='available_quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='buy_date',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='buying_price',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='car_type',
            new_name='type_of_car',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='borrow',
            new_name='loan',
        ),
        migrations.RemoveField(
            model_name='item',
            name='store_place',
        ),
        migrations.DeleteModel(
            name='StorePlace',
        ),
        migrations.AddField(
            model_name='item',
            name='shelf',
            field=models.ManyToManyField(to='spare.StoreShelf'),
        ),
    ]
