# Generated by Django 2.1.10 on 2019-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0003_auto_20190827_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_of_car',
            field=models.ManyToManyField(blank=True, to='spare.Vehicle'),
        ),
    ]
