# Generated by Django 2.1.10 on 2019-08-27 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0004_auto_20190827_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
