# Generated by Django 2.1.10 on 2019-08-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0005_auto_20190827_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeshelf',
            old_name='shelf_code',
            new_name='name',
        ),
    ]
