# Generated by Django 2.1.10 on 2019-08-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0006_auto_20190828_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='car',
            new_name='name',
        ),
    ]
