# Generated by Django 2.1.10 on 2019-08-29 12:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0008_auto_20190829_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
