# Generated by Django 2.1.10 on 2019-08-21 11:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='user name')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format : 09******** or +2519******** up to 15 digits allowed', regex='^\\+?1?\\d{10,15}$')])),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('photo', models.ImageField(blank=True, default='null.png', upload_to='')),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('manager', 'manager'), ('seller', 'seller')], max_length=200)),
                ('register_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
